# Linux Makefile for G0 Analysis Code
# (modified version of $(ROOTSYS)/test/Makefile)
#
# March 3, 2000  Author: W. Korsch

ObjSuf        = o
SrcSuf        = C
ExeSuf        =
DllSuf        = so
EVENTLIB      = $(EVENTO)
OutPutOpt     = -o  

ROOTCFLAGS    = $(shell root-config --cflags)
ROOTLIBS      = $(shell root-config --libs) 
ROOTGLIBS     = $(shell root-config --glibs)

# Linux with egcs
CXX           = g++
CXXFLAGS      = -O2 -Wall -fPIC 
LD            = g++
LDFLAGS       = -g
SOFLAGS       = -shared

CXXFLAGS     += $(ROOTCFLAGS)
LIBS          = $(ROOTLIBS) 
#GLIBS         = $(ROOTGLIBS)

MAIN = prepareCorrelationData.$(SrcSuf) 

SRCS = $(MAIN) 

OBJS = prepareCorrelationData.$(ObjSuf) 


EXE = prepareCorrelationData

$(EXE): $(OBJS) 
	$(CXX) $(CXXFLAGS) -o $(EXE) $(OBJS)  $(LIBS) $(GLIBS) 

all: depend $(EXE)

	@echo "---------------------> $(EXE) done <---------------------- "

depend .depend : $(SRCS)
	$(CXX) $(CXXFLAGS) -M $(MAIN)  >./.depend

clean:
		@rm -f $(OBJS) *~  core

cleanall:
		@rm -f $(OBJS) $(EXE) *~  core





